### ISSUE TITLE
User type doesn't match the credhub api docs

### ISSUE THREAD

**Issue by ctaymor** [cloudfoundry/docs-credhub#11]
In the Credhub Credential type docs, user says it's a single field. However, in the API docs, it has a username, password, and password has field. Seems like one version of the docs is out of date.

Credential Type Docs:
https://github.com/cloudfoundry/docs-credhub/blob/master/credential-types.html.md.erb#L37-L38

Api docs: http://credhub-api.cfapps.io/version/2.1/#type-user

**Comment by seviet** [comment]
Thank you for reporting this @ctaymor! We confirmed that the CredHub API docs are, in fact, correct and have updated the CF CredHub docs.
