### ISSUE TITLE
1st column wraps after only 2 characters

### ISSUE THREAD

**Issue by jbayer** [cloudfoundry/docs-credhub#6]
as rendered in chrome, the column for credential types is wrapping after just 2 characters without completing the word on each line. seems like the spacing could be better:  https://docs.pivotal.io/pivotalcf/2-2/credhub/credential-types.html

**Comment by animatedmax** [comment]
Hi @jbayer 
We pushed fix out for this 6 or 7 days ago, but our push never made it past the staging site. I've pushed it to staging, and the team leaders are working on a system to make sure all production content gets updated regularly.

I'm also checking other documentation versions to make sure the column fix shows up there, too.
 
Thanks!
